default:
  path: stylesheets
  # semantic_classes:
  #   "#footer, #header": ".span-24, div.span-24"
  #   "#content": ".span-17, div.span-17, div.colborder"
  #   "#extra-content": ".span-6, div.span-6"
  #   "div#navigation": "div.span_24, .span-24"
  #   "div.section, div.entry, .feeds": ".span-6 div.span-6"
